### ISSUE TITLE
runme open:Signature verification was not executed

### ISSUE THREAD

**Issue by agardnerIT** [runmedev/runme#718]
## OS

MacOS 15.2

## Runme version

```
% runme --version
runme version 3.10.2 (e46295933053f27a6c355adc715b448b86cb1da5) on 2024-12-17T20:14:53Z
```

## Full Error

```
% runme open
Installing extensions...
Installing extension 'stateful.runme'...
Error while installing extension stateful.runme: Signature verification was not executed.
Failed Installing Extensions: stateful.runme
[2024-12-22T01:27:50.408Z] error parent:41926 Uncaught exception: Signature verification was not executed.
[2024-12-22T01:27:50.412Z] error parent:41926 SignatureVerificationInternal: Signature verification was not executed.
    at Hc.ub (file:///opt/homebrew/Cellar/code-server/4.96.1/libexec/lib/vscode/out/server-main.js:58:17105)
    at async Hc.tb (file:///opt/homebrew/Cellar/code-server/4.96.1/libexec/lib/vscode/out/server-main.js:58:15571)
could not execute command: failed to install extension to code-server: code-server command failed: exit status 1
```

**Comment by sourishkrout** [comment]
Thanks for filing the issue, @agardnerIT.

@pastuxso, let's plan to look into this after the holidays when there is a moment.
